DROP TABLE IF EXISTS MATRICULAS;
DROP TABLE IF EXISTS DEPARTAMENTOS;
DROP TABLE IF EXISTS CONCLUIDAS;
DROP TABLE IF EXISTS CURSOS_TEM_DISCIPLINAS;
DROP TABLE IF EXISTS CURSOS;
DROP TABLE IF EXISTS ALUNOS;
DROP TABLE IF EXISTS PREREQUISITOS;
DROP TABLE IF EXISTS DISCIPLINAS;

CREATE TABLE DEPARTAMENTOS (
  codigo INTEGER,
  detalhes VARCHAR (100),
  PRIMARY KEY (codigo)
);

CREATE TABLE CURSOS (
  nome VARCHAR (100),
  codigo_departamento INTEGER NOT NULL,
  nome_curso VARCHAR(100),
  FOREIGN KEY (codigo_departamento) REFERENCES DEPARTAMENTOS (codigo),
  FOREIGN KEY (nome_curso) REFERENCES CURSOS (nome),
  PRIMARY KEY (nome)
);

CREATE TABLE ALUNOS (
  ra INT,
  nome VARCHAR(100),
  PRIMARY KEY (ra)
);

CREATE TABLE DISCIPLINAS (
  nome VARCHAR (100),
  PRIMARY KEY (nome)
);

CREATE TABLE MATRICULAS (
  nome_disciplina VARCHAR(100),
  ra_aluno INTEGER,
  FOREIGN KEY (nome_disciplina) REFERENCES DISCIPLINAS(nome),
  FOREIGN KEY (ra_aluno) REFERENCES ALUNOS(ra),
  PRIMARY KEY (nome_disciplina, ra_aluno)
);

CREATE TABLE CONCLUIDAS (
  nome_disciplina VARCHAR(100),
  ra_aluno INTEGER,
  FOREIGN KEY (nome_disciplina) REFERENCES DISCIPLINAS(nome),
  FOREIGN KEY (ra_aluno) REFERENCES ALUNOS(ra),
  PRIMARY KEY (nome_disciplina, ra_aluno)
);

CREATE TABLE PREREQUISITOS (
    nome_disciplina1 VARCHAR(100),
    nome_disciplina2 VARCHAR(100),
    FOREIGN KEY (nome_disciplina1) REFERENCES DISCIPLINAS(nome),
    FOREIGN KEY (nome_disciplina2) REFERENCES DISCIPLINAS(nome),
    PRIMARY KEY (nome_disciplina1, nome_disciplina2)
);

CREATE TABLE CURSOS_TEM_DISCIPLINAS (
    nome_curso VARCHAR (100),
    nome_disciplina VARCHAR (100),
    tipo ENUM ("Optativa", "Obrigatoria"), 
    FOREIGN KEY (nome_curso) REFERENCES CURSOS (nome),
    FOREIGN KEY (nome_disciplina) REFERENCES DISCIPLINAS(nome),
    PRIMARY KEY (nome_curso, nome_disciplina)
);

INSERT INTO CURSOS(nome) VALUES ("Ciência da Computação");