// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movies.proto

package org.example.structs;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moviesPackage.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
