// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movies.proto

package org.example.structs;

public interface MoviesListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moviesPackage.MoviesList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .moviesPackage.Movie movies = 1;</code>
   */
  java.util.List<org.example.structs.Movie> 
      getMoviesList();
  /**
   * <code>repeated .moviesPackage.Movie movies = 1;</code>
   */
  org.example.structs.Movie getMovies(int index);
  /**
   * <code>repeated .moviesPackage.Movie movies = 1;</code>
   */
  int getMoviesCount();
  /**
   * <code>repeated .moviesPackage.Movie movies = 1;</code>
   */
  java.util.List<? extends org.example.structs.MovieOrBuilder> 
      getMoviesOrBuilderList();
  /**
   * <code>repeated .moviesPackage.Movie movies = 1;</code>
   */
  org.example.structs.MovieOrBuilder getMoviesOrBuilder(
      int index);
}
