// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movies.proto

package org.example.structs;

public interface MovieOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moviesPackage.Movie)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string plot = 2;</code>
   */
  java.lang.String getPlot();
  /**
   * <code>string plot = 2;</code>
   */
  com.google.protobuf.ByteString
      getPlotBytes();

  /**
   * <code>string genre = 3;</code>
   */
  java.lang.String getGenre();
  /**
   * <code>string genre = 3;</code>
   */
  com.google.protobuf.ByteString
      getGenreBytes();

  /**
   * <code>int32 runtime = 4;</code>
   */
  int getRuntime();

  /**
   * <code>repeated string cast = 5;</code>
   */
  java.util.List<java.lang.String>
      getCastList();
  /**
   * <code>repeated string cast = 5;</code>
   */
  int getCastCount();
  /**
   * <code>repeated string cast = 5;</code>
   */
  java.lang.String getCast(int index);
  /**
   * <code>repeated string cast = 5;</code>
   */
  com.google.protobuf.ByteString
      getCastBytes(int index);

  /**
   * <code>int32 num_mflix_comments = 6;</code>
   */
  int getNumMflixComments();

  /**
   * <code>string title = 7;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 7;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string fullplot = 8;</code>
   */
  java.lang.String getFullplot();
  /**
   * <code>string fullplot = 8;</code>
   */
  com.google.protobuf.ByteString
      getFullplotBytes();

  /**
   * <code>repeated string countries = 9;</code>
   */
  java.util.List<java.lang.String>
      getCountriesList();
  /**
   * <code>repeated string countries = 9;</code>
   */
  int getCountriesCount();
  /**
   * <code>repeated string countries = 9;</code>
   */
  java.lang.String getCountries(int index);
  /**
   * <code>repeated string countries = 9;</code>
   */
  com.google.protobuf.ByteString
      getCountriesBytes(int index);

  /**
   * <code>string released = 10;</code>
   */
  java.lang.String getReleased();
  /**
   * <code>string released = 10;</code>
   */
  com.google.protobuf.ByteString
      getReleasedBytes();

  /**
   * <code>repeated string directors = 11;</code>
   */
  java.util.List<java.lang.String>
      getDirectorsList();
  /**
   * <code>repeated string directors = 11;</code>
   */
  int getDirectorsCount();
  /**
   * <code>repeated string directors = 11;</code>
   */
  java.lang.String getDirectors(int index);
  /**
   * <code>repeated string directors = 11;</code>
   */
  com.google.protobuf.ByteString
      getDirectorsBytes(int index);

  /**
   * <code>string rated = 12;</code>
   */
  java.lang.String getRated();
  /**
   * <code>string rated = 12;</code>
   */
  com.google.protobuf.ByteString
      getRatedBytes();

  /**
   * <code>string lastupdated = 13;</code>
   */
  java.lang.String getLastupdated();
  /**
   * <code>string lastupdated = 13;</code>
   */
  com.google.protobuf.ByteString
      getLastupdatedBytes();

  /**
   * <code>int32 year = 14;</code>
   */
  int getYear();

  /**
   * <code>string type = 15;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 15;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
