// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movies.proto

package org.example.structs;

public final class Movies {
  private Movies() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moviesPackage_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_moviesPackage_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moviesPackage_MoviesList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_moviesPackage_MoviesList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moviesPackage_Movie_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_moviesPackage_Movie_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014movies.proto\022\rmoviesPackage\"\032\n\007Message" +
      "\022\017\n\007message\030\001 \001(\t\"2\n\nMoviesList\022$\n\006movie" +
      "s\030\001 \003(\0132\024.moviesPackage.Movie\"\204\002\n\005Movie\022" +
      "\n\n\002id\030\001 \001(\t\022\014\n\004plot\030\002 \001(\t\022\r\n\005genre\030\003 \001(\t" +
      "\022\017\n\007runtime\030\004 \001(\005\022\014\n\004cast\030\005 \003(\t\022\032\n\022num_m" +
      "flix_comments\030\006 \001(\005\022\r\n\005title\030\007 \001(\t\022\020\n\010fu" +
      "llplot\030\010 \001(\t\022\021\n\tcountries\030\t \003(\t\022\020\n\010relea" +
      "sed\030\n \001(\t\022\021\n\tdirectors\030\013 \003(\t\022\r\n\005rated\030\014 " +
      "\001(\t\022\023\n\013lastupdated\030\r \001(\t\022\014\n\004year\030\016 \001(\005\022\014" +
      "\n\004type\030\017 \001(\t2\235\003\n\014MovieService\022=\n\013CreateM",
      "ovie\022\024.moviesPackage.Movie\032\026.moviesPacka" +
      "ge.Message\"\000\022:\n\010GetMovie\022\026.moviesPackage" +
      ".Message\032\024.moviesPackage.Movie\"\000\022=\n\013Upda" +
      "teMovie\022\024.moviesPackage.Movie\032\026.moviesPa" +
      "ckage.Message\"\000\022?\n\013DeleteMovie\022\026.moviesP" +
      "ackage.Message\032\026.moviesPackage.Message\"\000" +
      "\022H\n\021ListMoviesByActor\022\026.moviesPackage.Me" +
      "ssage\032\031.moviesPackage.MoviesList\"\000\022H\n\021Li" +
      "stMoviesByGenre\022\026.moviesPackage.Message\032" +
      "\031.moviesPackage.MoviesList\"\000B\027\n\023org.exam",
      "ple.structsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_moviesPackage_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_moviesPackage_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_moviesPackage_Message_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_moviesPackage_MoviesList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_moviesPackage_MoviesList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_moviesPackage_MoviesList_descriptor,
        new java.lang.String[] { "Movies", });
    internal_static_moviesPackage_Movie_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_moviesPackage_Movie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_moviesPackage_Movie_descriptor,
        new java.lang.String[] { "Id", "Plot", "Genre", "Runtime", "Cast", "NumMflixComments", "Title", "Fullplot", "Countries", "Released", "Directors", "Rated", "Lastupdated", "Year", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
