// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movies.proto

package org.example.structs;

/**
 * <pre>
 * The Movie definition that is used to send a movie
 * </pre>
 *
 * Protobuf type {@code moviesPackage.Movie}
 */
public  final class Movie extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:moviesPackage.Movie)
    MovieOrBuilder {
  // Use Movie.newBuilder() to construct.
  private Movie(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Movie() {
    id_ = "";
    plot_ = "";
    genre_ = "";
    runtime_ = 0;
    cast_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    numMflixComments_ = 0;
    title_ = "";
    fullplot_ = "";
    countries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    released_ = "";
    directors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    rated_ = "";
    lastupdated_ = "";
    year_ = 0;
    type_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Movie(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            plot_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            genre_ = s;
            break;
          }
          case 32: {

            runtime_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              cast_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000010;
            }
            cast_.add(s);
            break;
          }
          case 48: {

            numMflixComments_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            fullplot_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
              countries_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000100;
            }
            countries_.add(s);
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            released_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
              directors_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000400;
            }
            directors_.add(s);
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            rated_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            lastupdated_ = s;
            break;
          }
          case 112: {

            year_ = input.readInt32();
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        cast_ = cast_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
        countries_ = countries_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
        directors_ = directors_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.structs.Movies.internal_static_moviesPackage_Movie_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.structs.Movies.internal_static_moviesPackage_Movie_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.structs.Movie.class, org.example.structs.Movie.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLOT_FIELD_NUMBER = 2;
  private volatile java.lang.Object plot_;
  /**
   * <code>string plot = 2;</code>
   */
  public java.lang.String getPlot() {
    java.lang.Object ref = plot_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      plot_ = s;
      return s;
    }
  }
  /**
   * <code>string plot = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPlotBytes() {
    java.lang.Object ref = plot_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      plot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENRE_FIELD_NUMBER = 3;
  private volatile java.lang.Object genre_;
  /**
   * <code>string genre = 3;</code>
   */
  public java.lang.String getGenre() {
    java.lang.Object ref = genre_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      genre_ = s;
      return s;
    }
  }
  /**
   * <code>string genre = 3;</code>
   */
  public com.google.protobuf.ByteString
      getGenreBytes() {
    java.lang.Object ref = genre_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      genre_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RUNTIME_FIELD_NUMBER = 4;
  private int runtime_;
  /**
   * <code>int32 runtime = 4;</code>
   */
  public int getRuntime() {
    return runtime_;
  }

  public static final int CAST_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList cast_;
  /**
   * <code>repeated string cast = 5;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getCastList() {
    return cast_;
  }
  /**
   * <code>repeated string cast = 5;</code>
   */
  public int getCastCount() {
    return cast_.size();
  }
  /**
   * <code>repeated string cast = 5;</code>
   */
  public java.lang.String getCast(int index) {
    return cast_.get(index);
  }
  /**
   * <code>repeated string cast = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCastBytes(int index) {
    return cast_.getByteString(index);
  }

  public static final int NUM_MFLIX_COMMENTS_FIELD_NUMBER = 6;
  private int numMflixComments_;
  /**
   * <code>int32 num_mflix_comments = 6;</code>
   */
  public int getNumMflixComments() {
    return numMflixComments_;
  }

  public static final int TITLE_FIELD_NUMBER = 7;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 7;</code>
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 7;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FULLPLOT_FIELD_NUMBER = 8;
  private volatile java.lang.Object fullplot_;
  /**
   * <code>string fullplot = 8;</code>
   */
  public java.lang.String getFullplot() {
    java.lang.Object ref = fullplot_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fullplot_ = s;
      return s;
    }
  }
  /**
   * <code>string fullplot = 8;</code>
   */
  public com.google.protobuf.ByteString
      getFullplotBytes() {
    java.lang.Object ref = fullplot_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fullplot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUNTRIES_FIELD_NUMBER = 9;
  private com.google.protobuf.LazyStringList countries_;
  /**
   * <code>repeated string countries = 9;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getCountriesList() {
    return countries_;
  }
  /**
   * <code>repeated string countries = 9;</code>
   */
  public int getCountriesCount() {
    return countries_.size();
  }
  /**
   * <code>repeated string countries = 9;</code>
   */
  public java.lang.String getCountries(int index) {
    return countries_.get(index);
  }
  /**
   * <code>repeated string countries = 9;</code>
   */
  public com.google.protobuf.ByteString
      getCountriesBytes(int index) {
    return countries_.getByteString(index);
  }

  public static final int RELEASED_FIELD_NUMBER = 10;
  private volatile java.lang.Object released_;
  /**
   * <code>string released = 10;</code>
   */
  public java.lang.String getReleased() {
    java.lang.Object ref = released_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      released_ = s;
      return s;
    }
  }
  /**
   * <code>string released = 10;</code>
   */
  public com.google.protobuf.ByteString
      getReleasedBytes() {
    java.lang.Object ref = released_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      released_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIRECTORS_FIELD_NUMBER = 11;
  private com.google.protobuf.LazyStringList directors_;
  /**
   * <code>repeated string directors = 11;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getDirectorsList() {
    return directors_;
  }
  /**
   * <code>repeated string directors = 11;</code>
   */
  public int getDirectorsCount() {
    return directors_.size();
  }
  /**
   * <code>repeated string directors = 11;</code>
   */
  public java.lang.String getDirectors(int index) {
    return directors_.get(index);
  }
  /**
   * <code>repeated string directors = 11;</code>
   */
  public com.google.protobuf.ByteString
      getDirectorsBytes(int index) {
    return directors_.getByteString(index);
  }

  public static final int RATED_FIELD_NUMBER = 12;
  private volatile java.lang.Object rated_;
  /**
   * <code>string rated = 12;</code>
   */
  public java.lang.String getRated() {
    java.lang.Object ref = rated_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rated_ = s;
      return s;
    }
  }
  /**
   * <code>string rated = 12;</code>
   */
  public com.google.protobuf.ByteString
      getRatedBytes() {
    java.lang.Object ref = rated_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rated_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTUPDATED_FIELD_NUMBER = 13;
  private volatile java.lang.Object lastupdated_;
  /**
   * <code>string lastupdated = 13;</code>
   */
  public java.lang.String getLastupdated() {
    java.lang.Object ref = lastupdated_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastupdated_ = s;
      return s;
    }
  }
  /**
   * <code>string lastupdated = 13;</code>
   */
  public com.google.protobuf.ByteString
      getLastupdatedBytes() {
    java.lang.Object ref = lastupdated_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastupdated_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int YEAR_FIELD_NUMBER = 14;
  private int year_;
  /**
   * <code>int32 year = 14;</code>
   */
  public int getYear() {
    return year_;
  }

  public static final int TYPE_FIELD_NUMBER = 15;
  private volatile java.lang.Object type_;
  /**
   * <code>string type = 15;</code>
   */
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 15;</code>
   */
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getPlotBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, plot_);
    }
    if (!getGenreBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, genre_);
    }
    if (runtime_ != 0) {
      output.writeInt32(4, runtime_);
    }
    for (int i = 0; i < cast_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cast_.getRaw(i));
    }
    if (numMflixComments_ != 0) {
      output.writeInt32(6, numMflixComments_);
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, title_);
    }
    if (!getFullplotBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, fullplot_);
    }
    for (int i = 0; i < countries_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, countries_.getRaw(i));
    }
    if (!getReleasedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, released_);
    }
    for (int i = 0; i < directors_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, directors_.getRaw(i));
    }
    if (!getRatedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, rated_);
    }
    if (!getLastupdatedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, lastupdated_);
    }
    if (year_ != 0) {
      output.writeInt32(14, year_);
    }
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, type_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getPlotBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, plot_);
    }
    if (!getGenreBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, genre_);
    }
    if (runtime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, runtime_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < cast_.size(); i++) {
        dataSize += computeStringSizeNoTag(cast_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCastList().size();
    }
    if (numMflixComments_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, numMflixComments_);
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, title_);
    }
    if (!getFullplotBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, fullplot_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < countries_.size(); i++) {
        dataSize += computeStringSizeNoTag(countries_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCountriesList().size();
    }
    if (!getReleasedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, released_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < directors_.size(); i++) {
        dataSize += computeStringSizeNoTag(directors_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDirectorsList().size();
    }
    if (!getRatedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, rated_);
    }
    if (!getLastupdatedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, lastupdated_);
    }
    if (year_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, year_);
    }
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, type_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.structs.Movie)) {
      return super.equals(obj);
    }
    org.example.structs.Movie other = (org.example.structs.Movie) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getPlot()
        .equals(other.getPlot());
    result = result && getGenre()
        .equals(other.getGenre());
    result = result && (getRuntime()
        == other.getRuntime());
    result = result && getCastList()
        .equals(other.getCastList());
    result = result && (getNumMflixComments()
        == other.getNumMflixComments());
    result = result && getTitle()
        .equals(other.getTitle());
    result = result && getFullplot()
        .equals(other.getFullplot());
    result = result && getCountriesList()
        .equals(other.getCountriesList());
    result = result && getReleased()
        .equals(other.getReleased());
    result = result && getDirectorsList()
        .equals(other.getDirectorsList());
    result = result && getRated()
        .equals(other.getRated());
    result = result && getLastupdated()
        .equals(other.getLastupdated());
    result = result && (getYear()
        == other.getYear());
    result = result && getType()
        .equals(other.getType());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + PLOT_FIELD_NUMBER;
    hash = (53 * hash) + getPlot().hashCode();
    hash = (37 * hash) + GENRE_FIELD_NUMBER;
    hash = (53 * hash) + getGenre().hashCode();
    hash = (37 * hash) + RUNTIME_FIELD_NUMBER;
    hash = (53 * hash) + getRuntime();
    if (getCastCount() > 0) {
      hash = (37 * hash) + CAST_FIELD_NUMBER;
      hash = (53 * hash) + getCastList().hashCode();
    }
    hash = (37 * hash) + NUM_MFLIX_COMMENTS_FIELD_NUMBER;
    hash = (53 * hash) + getNumMflixComments();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + FULLPLOT_FIELD_NUMBER;
    hash = (53 * hash) + getFullplot().hashCode();
    if (getCountriesCount() > 0) {
      hash = (37 * hash) + COUNTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getCountriesList().hashCode();
    }
    hash = (37 * hash) + RELEASED_FIELD_NUMBER;
    hash = (53 * hash) + getReleased().hashCode();
    if (getDirectorsCount() > 0) {
      hash = (37 * hash) + DIRECTORS_FIELD_NUMBER;
      hash = (53 * hash) + getDirectorsList().hashCode();
    }
    hash = (37 * hash) + RATED_FIELD_NUMBER;
    hash = (53 * hash) + getRated().hashCode();
    hash = (37 * hash) + LASTUPDATED_FIELD_NUMBER;
    hash = (53 * hash) + getLastupdated().hashCode();
    hash = (37 * hash) + YEAR_FIELD_NUMBER;
    hash = (53 * hash) + getYear();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.structs.Movie parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.structs.Movie parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.structs.Movie parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.structs.Movie parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.structs.Movie parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.structs.Movie parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.structs.Movie parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.structs.Movie parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.structs.Movie parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.example.structs.Movie parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.structs.Movie parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.structs.Movie parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.structs.Movie prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The Movie definition that is used to send a movie
   * </pre>
   *
   * Protobuf type {@code moviesPackage.Movie}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:moviesPackage.Movie)
      org.example.structs.MovieOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.structs.Movies.internal_static_moviesPackage_Movie_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.structs.Movies.internal_static_moviesPackage_Movie_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.structs.Movie.class, org.example.structs.Movie.Builder.class);
    }

    // Construct using org.example.structs.Movie.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = "";

      plot_ = "";

      genre_ = "";

      runtime_ = 0;

      cast_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      numMflixComments_ = 0;

      title_ = "";

      fullplot_ = "";

      countries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000100);
      released_ = "";

      directors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000400);
      rated_ = "";

      lastupdated_ = "";

      year_ = 0;

      type_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.structs.Movies.internal_static_moviesPackage_Movie_descriptor;
    }

    public org.example.structs.Movie getDefaultInstanceForType() {
      return org.example.structs.Movie.getDefaultInstance();
    }

    public org.example.structs.Movie build() {
      org.example.structs.Movie result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.example.structs.Movie buildPartial() {
      org.example.structs.Movie result = new org.example.structs.Movie(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.plot_ = plot_;
      result.genre_ = genre_;
      result.runtime_ = runtime_;
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        cast_ = cast_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.cast_ = cast_;
      result.numMflixComments_ = numMflixComments_;
      result.title_ = title_;
      result.fullplot_ = fullplot_;
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        countries_ = countries_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000100);
      }
      result.countries_ = countries_;
      result.released_ = released_;
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        directors_ = directors_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000400);
      }
      result.directors_ = directors_;
      result.rated_ = rated_;
      result.lastupdated_ = lastupdated_;
      result.year_ = year_;
      result.type_ = type_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.structs.Movie) {
        return mergeFrom((org.example.structs.Movie)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.structs.Movie other) {
      if (other == org.example.structs.Movie.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getPlot().isEmpty()) {
        plot_ = other.plot_;
        onChanged();
      }
      if (!other.getGenre().isEmpty()) {
        genre_ = other.genre_;
        onChanged();
      }
      if (other.getRuntime() != 0) {
        setRuntime(other.getRuntime());
      }
      if (!other.cast_.isEmpty()) {
        if (cast_.isEmpty()) {
          cast_ = other.cast_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureCastIsMutable();
          cast_.addAll(other.cast_);
        }
        onChanged();
      }
      if (other.getNumMflixComments() != 0) {
        setNumMflixComments(other.getNumMflixComments());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getFullplot().isEmpty()) {
        fullplot_ = other.fullplot_;
        onChanged();
      }
      if (!other.countries_.isEmpty()) {
        if (countries_.isEmpty()) {
          countries_ = other.countries_;
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          ensureCountriesIsMutable();
          countries_.addAll(other.countries_);
        }
        onChanged();
      }
      if (!other.getReleased().isEmpty()) {
        released_ = other.released_;
        onChanged();
      }
      if (!other.directors_.isEmpty()) {
        if (directors_.isEmpty()) {
          directors_ = other.directors_;
          bitField0_ = (bitField0_ & ~0x00000400);
        } else {
          ensureDirectorsIsMutable();
          directors_.addAll(other.directors_);
        }
        onChanged();
      }
      if (!other.getRated().isEmpty()) {
        rated_ = other.rated_;
        onChanged();
      }
      if (!other.getLastupdated().isEmpty()) {
        lastupdated_ = other.lastupdated_;
        onChanged();
      }
      if (other.getYear() != 0) {
        setYear(other.getYear());
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.example.structs.Movie parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.example.structs.Movie) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object plot_ = "";
    /**
     * <code>string plot = 2;</code>
     */
    public java.lang.String getPlot() {
      java.lang.Object ref = plot_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        plot_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string plot = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPlotBytes() {
      java.lang.Object ref = plot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        plot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string plot = 2;</code>
     */
    public Builder setPlot(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      plot_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string plot = 2;</code>
     */
    public Builder clearPlot() {
      
      plot_ = getDefaultInstance().getPlot();
      onChanged();
      return this;
    }
    /**
     * <code>string plot = 2;</code>
     */
    public Builder setPlotBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      plot_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object genre_ = "";
    /**
     * <code>string genre = 3;</code>
     */
    public java.lang.String getGenre() {
      java.lang.Object ref = genre_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        genre_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string genre = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGenreBytes() {
      java.lang.Object ref = genre_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genre_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string genre = 3;</code>
     */
    public Builder setGenre(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      genre_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string genre = 3;</code>
     */
    public Builder clearGenre() {
      
      genre_ = getDefaultInstance().getGenre();
      onChanged();
      return this;
    }
    /**
     * <code>string genre = 3;</code>
     */
    public Builder setGenreBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      genre_ = value;
      onChanged();
      return this;
    }

    private int runtime_ ;
    /**
     * <code>int32 runtime = 4;</code>
     */
    public int getRuntime() {
      return runtime_;
    }
    /**
     * <code>int32 runtime = 4;</code>
     */
    public Builder setRuntime(int value) {
      
      runtime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 runtime = 4;</code>
     */
    public Builder clearRuntime() {
      
      runtime_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList cast_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCastIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        cast_ = new com.google.protobuf.LazyStringArrayList(cast_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <code>repeated string cast = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCastList() {
      return cast_.getUnmodifiableView();
    }
    /**
     * <code>repeated string cast = 5;</code>
     */
    public int getCastCount() {
      return cast_.size();
    }
    /**
     * <code>repeated string cast = 5;</code>
     */
    public java.lang.String getCast(int index) {
      return cast_.get(index);
    }
    /**
     * <code>repeated string cast = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCastBytes(int index) {
      return cast_.getByteString(index);
    }
    /**
     * <code>repeated string cast = 5;</code>
     */
    public Builder setCast(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCastIsMutable();
      cast_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cast = 5;</code>
     */
    public Builder addCast(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCastIsMutable();
      cast_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cast = 5;</code>
     */
    public Builder addAllCast(
        java.lang.Iterable<java.lang.String> values) {
      ensureCastIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, cast_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cast = 5;</code>
     */
    public Builder clearCast() {
      cast_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cast = 5;</code>
     */
    public Builder addCastBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCastIsMutable();
      cast_.add(value);
      onChanged();
      return this;
    }

    private int numMflixComments_ ;
    /**
     * <code>int32 num_mflix_comments = 6;</code>
     */
    public int getNumMflixComments() {
      return numMflixComments_;
    }
    /**
     * <code>int32 num_mflix_comments = 6;</code>
     */
    public Builder setNumMflixComments(int value) {
      
      numMflixComments_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 num_mflix_comments = 6;</code>
     */
    public Builder clearNumMflixComments() {
      
      numMflixComments_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 7;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 7;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 7;</code>
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 7;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fullplot_ = "";
    /**
     * <code>string fullplot = 8;</code>
     */
    public java.lang.String getFullplot() {
      java.lang.Object ref = fullplot_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fullplot_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fullplot = 8;</code>
     */
    public com.google.protobuf.ByteString
        getFullplotBytes() {
      java.lang.Object ref = fullplot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullplot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fullplot = 8;</code>
     */
    public Builder setFullplot(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fullplot_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fullplot = 8;</code>
     */
    public Builder clearFullplot() {
      
      fullplot_ = getDefaultInstance().getFullplot();
      onChanged();
      return this;
    }
    /**
     * <code>string fullplot = 8;</code>
     */
    public Builder setFullplotBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fullplot_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList countries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCountriesIsMutable() {
      if (!((bitField0_ & 0x00000100) == 0x00000100)) {
        countries_ = new com.google.protobuf.LazyStringArrayList(countries_);
        bitField0_ |= 0x00000100;
       }
    }
    /**
     * <code>repeated string countries = 9;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCountriesList() {
      return countries_.getUnmodifiableView();
    }
    /**
     * <code>repeated string countries = 9;</code>
     */
    public int getCountriesCount() {
      return countries_.size();
    }
    /**
     * <code>repeated string countries = 9;</code>
     */
    public java.lang.String getCountries(int index) {
      return countries_.get(index);
    }
    /**
     * <code>repeated string countries = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCountriesBytes(int index) {
      return countries_.getByteString(index);
    }
    /**
     * <code>repeated string countries = 9;</code>
     */
    public Builder setCountries(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCountriesIsMutable();
      countries_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string countries = 9;</code>
     */
    public Builder addCountries(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCountriesIsMutable();
      countries_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string countries = 9;</code>
     */
    public Builder addAllCountries(
        java.lang.Iterable<java.lang.String> values) {
      ensureCountriesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, countries_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string countries = 9;</code>
     */
    public Builder clearCountries() {
      countries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string countries = 9;</code>
     */
    public Builder addCountriesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCountriesIsMutable();
      countries_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object released_ = "";
    /**
     * <code>string released = 10;</code>
     */
    public java.lang.String getReleased() {
      java.lang.Object ref = released_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        released_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string released = 10;</code>
     */
    public com.google.protobuf.ByteString
        getReleasedBytes() {
      java.lang.Object ref = released_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        released_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string released = 10;</code>
     */
    public Builder setReleased(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      released_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string released = 10;</code>
     */
    public Builder clearReleased() {
      
      released_ = getDefaultInstance().getReleased();
      onChanged();
      return this;
    }
    /**
     * <code>string released = 10;</code>
     */
    public Builder setReleasedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      released_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList directors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureDirectorsIsMutable() {
      if (!((bitField0_ & 0x00000400) == 0x00000400)) {
        directors_ = new com.google.protobuf.LazyStringArrayList(directors_);
        bitField0_ |= 0x00000400;
       }
    }
    /**
     * <code>repeated string directors = 11;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDirectorsList() {
      return directors_.getUnmodifiableView();
    }
    /**
     * <code>repeated string directors = 11;</code>
     */
    public int getDirectorsCount() {
      return directors_.size();
    }
    /**
     * <code>repeated string directors = 11;</code>
     */
    public java.lang.String getDirectors(int index) {
      return directors_.get(index);
    }
    /**
     * <code>repeated string directors = 11;</code>
     */
    public com.google.protobuf.ByteString
        getDirectorsBytes(int index) {
      return directors_.getByteString(index);
    }
    /**
     * <code>repeated string directors = 11;</code>
     */
    public Builder setDirectors(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDirectorsIsMutable();
      directors_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string directors = 11;</code>
     */
    public Builder addDirectors(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDirectorsIsMutable();
      directors_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string directors = 11;</code>
     */
    public Builder addAllDirectors(
        java.lang.Iterable<java.lang.String> values) {
      ensureDirectorsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, directors_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string directors = 11;</code>
     */
    public Builder clearDirectors() {
      directors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string directors = 11;</code>
     */
    public Builder addDirectorsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureDirectorsIsMutable();
      directors_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object rated_ = "";
    /**
     * <code>string rated = 12;</code>
     */
    public java.lang.String getRated() {
      java.lang.Object ref = rated_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rated_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string rated = 12;</code>
     */
    public com.google.protobuf.ByteString
        getRatedBytes() {
      java.lang.Object ref = rated_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rated_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string rated = 12;</code>
     */
    public Builder setRated(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string rated = 12;</code>
     */
    public Builder clearRated() {
      
      rated_ = getDefaultInstance().getRated();
      onChanged();
      return this;
    }
    /**
     * <code>string rated = 12;</code>
     */
    public Builder setRatedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      rated_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastupdated_ = "";
    /**
     * <code>string lastupdated = 13;</code>
     */
    public java.lang.String getLastupdated() {
      java.lang.Object ref = lastupdated_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastupdated_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lastupdated = 13;</code>
     */
    public com.google.protobuf.ByteString
        getLastupdatedBytes() {
      java.lang.Object ref = lastupdated_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastupdated_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lastupdated = 13;</code>
     */
    public Builder setLastupdated(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastupdated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lastupdated = 13;</code>
     */
    public Builder clearLastupdated() {
      
      lastupdated_ = getDefaultInstance().getLastupdated();
      onChanged();
      return this;
    }
    /**
     * <code>string lastupdated = 13;</code>
     */
    public Builder setLastupdatedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastupdated_ = value;
      onChanged();
      return this;
    }

    private int year_ ;
    /**
     * <code>int32 year = 14;</code>
     */
    public int getYear() {
      return year_;
    }
    /**
     * <code>int32 year = 14;</code>
     */
    public Builder setYear(int value) {
      
      year_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 year = 14;</code>
     */
    public Builder clearYear() {
      
      year_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 15;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 15;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 15;</code>
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 15;</code>
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string type = 15;</code>
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:moviesPackage.Movie)
  }

  // @@protoc_insertion_point(class_scope:moviesPackage.Movie)
  private static final org.example.structs.Movie DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.structs.Movie();
  }

  public static org.example.structs.Movie getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Movie>
      PARSER = new com.google.protobuf.AbstractParser<Movie>() {
    public Movie parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Movie(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Movie> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Movie> getParserForType() {
    return PARSER;
  }

  public org.example.structs.Movie getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

