C: 
	gcc nbody.c -o cnbody -lm
	time ./cnbody 10000000

Clang: 
	clang nbody.c -o clangnbody -lm
	time ./clangnbody 10000000

Python: 
	time python3 nbody.py 10000000

Pypy:
	time pypy3 nbody.py 10000000

Clear:
	rm ./cnbody
	rm ./clangnbody