C: 
	g++ binary_trees.cpp -o cbinary_trees
	time ./cbinary_trees 16

Clang: 
	clang++ binary_trees.cpp -o clangbinary_trees
	time ./clangbinary_trees 16

Python: 
	time python3 binary_trees.py 16

Pypy:
	time pypy3 binary_trees.py 16

Codon:
	codon run -release binary_trees.codon 16