client_run:
	clear;
	python3 client.py

classifier_run:
	clear;
	python3 classifier.py

collector_run:
	clear;
	python3 collector.py

setup:
	sudo pip install pika
	sudo pip install colorama

remove:
	rm *.pyc