# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movies.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmovies.proto\"/\n\rClientRequest\x12\x1e\n\toperation\x18\x01 \x01(\x0e\x32\x0b.Operations\"(\n\x11GetMovieOperation\x12\x13\n\x0bmovie_title\x18\x01 \x01(\t\"+\n\x14\x44\x65leteMovieOperation\x12\x13\n\x0bmovie_title\x18\x01 \x01(\t\"\"\n\x0eServerResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"%\n\x13\x43lientListOperation\x12\x0e\n\x06\x66ilter\x18\x01 \x01(\t\"&\n\x0cServerListBy\x12\x16\n\x06movies\x18\x01 \x03(\x0b\x32\x06.Movie\"\x84\x02\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04plot\x18\x02 \x01(\t\x12\r\n\x05genre\x18\x03 \x01(\t\x12\x0f\n\x07runtime\x18\x04 \x01(\x05\x12\x0c\n\x04\x63\x61st\x18\x05 \x03(\t\x12\x1a\n\x12num_mflix_comments\x18\x06 \x01(\x05\x12\r\n\x05title\x18\x07 \x01(\t\x12\x10\n\x08\x66ullplot\x18\x08 \x01(\t\x12\x11\n\tcountries\x18\t \x03(\t\x12\x10\n\x08released\x18\n \x01(\t\x12\x11\n\tdirectors\x18\x0b \x03(\t\x12\r\n\x05rated\x18\x0c \x01(\t\x12\x13\n\x0blastupdated\x18\r \x01(\t\x12\x0c\n\x04year\x18\x0e \x01(\x05\x12\x0c\n\x04type\x18\x0f \x01(\t*k\n\nOperations\x12\x08\n\x04Zero\x10\x00\x12\n\n\x06\x43reate\x10\x01\x12\x08\n\x04Read\x10\x02\x12\n\n\x06Update\x10\x03\x12\n\n\x06\x44\x65lete\x10\x04\x12\x10\n\x0cListByActors\x10\x05\x12\x13\n\x0fListByDirectors\x10\x06\x42\x1e\n\x1aorg.example.client.structsP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movies_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032org.example.client.structsP\001'
  _globals['_OPERATIONS']._serialized_start=530
  _globals['_OPERATIONS']._serialized_end=637
  _globals['_CLIENTREQUEST']._serialized_start=16
  _globals['_CLIENTREQUEST']._serialized_end=63
  _globals['_GETMOVIEOPERATION']._serialized_start=65
  _globals['_GETMOVIEOPERATION']._serialized_end=105
  _globals['_DELETEMOVIEOPERATION']._serialized_start=107
  _globals['_DELETEMOVIEOPERATION']._serialized_end=150
  _globals['_SERVERRESPONSE']._serialized_start=152
  _globals['_SERVERRESPONSE']._serialized_end=186
  _globals['_CLIENTLISTOPERATION']._serialized_start=188
  _globals['_CLIENTLISTOPERATION']._serialized_end=225
  _globals['_SERVERLISTBY']._serialized_start=227
  _globals['_SERVERLISTBY']._serialized_end=265
  _globals['_MOVIE']._serialized_start=268
  _globals['_MOVIE']._serialized_end=528
# @@protoc_insertion_point(module_scope)
