/* 1 - ENCONTRA O NOME E FATURAMENTO DAS LOJAS CUJO FATURAMENTO É MAIOR DO QUE O RESTAURANTE COM MAIOR FATURAMENTO */
SELECT L.nome, L.faturamento
FROM LOJAS L
WHERE L.faturamento > ALL 
	( 	SELECT R.faturamento
		FROM RESTAURANTES R
);

/* 2 - ENCONTRA OS NOMES DOS CLIENTES QUE NÃO ENTRARAM NAS LOJAS 7 e 25 */
SELECT C.nome
FROM CLIENTES C
WHERE C.cpf NOT IN
	( 	SELECT LC.cliente
		FROM LOJAS_CLIENTES LC
        WHERE LC.loja = 7 AND LC.loja = 25
);

/* 3 - ENCONTRA O NOME DAS LOJAS COM MAIS DE 5 PRODUTOS */
SELECT L.nome
FROM LOJAS L
WHERE L.numeroDoBox IN (
    SELECT PL.loja
    FROM PRODUTOS_LOJAS PL
        GROUP BY PL.produto
        HAVING COUNT(PL.produto) >= 5
);

/* 4 - ENCONTRA O NOME DOS RESTAURANTES QUE TEM UM CARDÁPIO DE HAMBURGER (18) OU DE PIZZA (26) */
SELECT R.nome
FROM RESTAURANTES R
WHERE R.codigoCardapio IN (
    SELECT C.codigoCardapio
    FROM CARDAPIOS C
    WHERE C.codigoCardapio = 18 OR C.codigoCardapio = 26
);

/* 5 - ENCONTRA O NOME DOS PRODUTOS VENDIDOS NA LOJA A E B */
SELECT P.NOME
FROM PRODUTOS P
WHERE P.codigoProduto IN (
    SELECT PL.produto
    FROM PRODUTOS_LOJAS PL
    WHERE PL.loja IN (
        SELECT L.numeroDoBox
        FROM LOJAS L
        WHERE L.NOME IN ('Magalu', 'CasasBahia')
    )
);

/* 6 - ENCONTRA O NOME DO CLIENTE QUE OCUPA MAIS DE UMA VAGA */
SELECT C.nome
FROM CLIENTES C
WHERE C.cpf IN (
    SELECT CV.cliente
    FROM CLIENTES_VAGAS CV
        GROUP BY CV.cliente
        HAVING COUNT(CV.cliente) > 1
);

/* 7 - ENCONTRA O NOME DO CLIENTE QUE VISITOU A LOJA E O RESTAURANTE COM MAIOR FATURAMENTO */
SELECT C.nome
FROM CLIENTES C
WHERE C.cpf IN (
    SELECT RC.cliente
    FROM RESTAURANTE_CLIENTES RC
	WHERE RC.restaurante IN (
		SELECT MAX(R.faturamento)
        FROM RESTAURANTES R
        GROUP BY R.faturamento)
    )
    AND 
    (
    SELECT LC.cliente
    FROM LOJAS_CLIENTES LC
	WHERE LC.loja IN (
		SELECT MAX(L.faturamento)
        FROM LOJAS L
        GROUP BY L.faturamento)
);	

/* 8 - ENCONTRA O NOME DOS CLIENTES QUE USAM VAGAS DE MOTOS */
SELECT C.nome
FROM CLIENTES C
WHERE C.numeroVaga IN (
    SELECT E.idVaga
    FROM ESTACIONAMENTOS E
    WHERE E.tipo = 'Moto'
);
    
/* 9 - ENCONTRA O NOME DOS CLIENTES QUE NÃO VISITARAM NENHUMA LOJA */
SELECT C.nome
FROM CLIENTES C
WHERE NOT EXISTS 
		(SELECT LC.cliente
        FROM LOJAS_CLIENTES LC
        WHERE LC.cliente = C.cpf
);
        
/* 10 - ENCONTRA O NOME DOS RESTAURANTES COM 3 OU MAIS CLIENTES */
SELECT DISTINCT R.nome 
FROM RESTAURANTES R
WHERE R.numeroDoBox IN (
    SELECT RC.restaurante
    FROM RESTAURANTE_CLIENTES RC
        GROUP BY RC.cliente
        HAVING COUNT(RC.cliente) >= 3
);