compile:
	clear; javac Server.java
	clear; javac Client.java

server:
	javac Server.java; clear; java Server

client:
	javac Client.java; clear; java Client

server-run:
	clear; java Server

client-run:
	clear; java Client