all:
	clear; python3 peer.py

tcp-server:
	clear; python3 peer.py
	# Preciso rodar ele em uma porta diferente? python3 peer.py -p 8000

requirements:
	pip install -r requirements.txt

remove:
	rm *.pyc