# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movies.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmovies.proto\x12\rmoviesPackage\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"2\n\nMoviesList\x12$\n\x06movies\x18\x01 \x03(\x0b\x32\x14.moviesPackage.Movie\"\x84\x02\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04plot\x18\x02 \x01(\t\x12\r\n\x05genre\x18\x03 \x01(\t\x12\x0f\n\x07runtime\x18\x04 \x01(\x05\x12\x0c\n\x04\x63\x61st\x18\x05 \x03(\t\x12\x1a\n\x12num_mflix_comments\x18\x06 \x01(\x05\x12\r\n\x05title\x18\x07 \x01(\t\x12\x10\n\x08\x66ullplot\x18\x08 \x01(\t\x12\x11\n\tcountries\x18\t \x03(\t\x12\x10\n\x08released\x18\n \x01(\t\x12\x11\n\tdirectors\x18\x0b \x03(\t\x12\r\n\x05rated\x18\x0c \x01(\t\x12\x13\n\x0blastupdated\x18\r \x01(\t\x12\x0c\n\x04year\x18\x0e \x01(\x05\x12\x0c\n\x04type\x18\x0f \x01(\t2\x9d\x03\n\x0cMovieService\x12=\n\x0b\x43reateMovie\x12\x14.moviesPackage.Movie\x1a\x16.moviesPackage.Message\"\x00\x12:\n\x08GetMovie\x12\x16.moviesPackage.Message\x1a\x14.moviesPackage.Movie\"\x00\x12=\n\x0bUpdateMovie\x12\x14.moviesPackage.Movie\x1a\x16.moviesPackage.Message\"\x00\x12?\n\x0b\x44\x65leteMovie\x12\x16.moviesPackage.Message\x1a\x16.moviesPackage.Message\"\x00\x12H\n\x11ListMoviesByActor\x12\x16.moviesPackage.Message\x1a\x19.moviesPackage.MoviesList\"\x00\x12H\n\x11ListMoviesByGenre\x12\x16.moviesPackage.Message\x1a\x19.moviesPackage.MoviesList\"\x00\x42\x1e\n\x1aorg.example.client.structsP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movies_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032org.example.client.structsP\001'
  _MESSAGE._serialized_start=31
  _MESSAGE._serialized_end=57
  _MOVIESLIST._serialized_start=59
  _MOVIESLIST._serialized_end=109
  _MOVIE._serialized_start=112
  _MOVIE._serialized_end=372
  _MOVIESERVICE._serialized_start=375
  _MOVIESERVICE._serialized_end=788
# @@protoc_insertion_point(module_scope)
