// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movies.proto

package org.example.client.structs;

public interface ClientListOperationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientListOperation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filter = 1;</code>
   * @return The filter.
   */
  java.lang.String getFilter();
  /**
   * <code>string filter = 1;</code>
   * @return The bytes for filter.
   */
  com.google.protobuf.ByteString
      getFilterBytes();
}
