// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movies.proto

package org.example.client.structs;

public interface ClientRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Operations operation = 1;</code>
   * @return The enum numeric value on the wire for operation.
   */
  int getOperationValue();
  /**
   * <code>.Operations operation = 1;</code>
   * @return The operation.
   */
  org.example.client.structs.Operations getOperation();
}
