// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movies.proto

package org.example.client.structs;

public interface DeleteMovieOperationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteMovieOperation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string movie_title = 1;</code>
   * @return The movieTitle.
   */
  java.lang.String getMovieTitle();
  /**
   * <code>string movie_title = 1;</code>
   * @return The bytes for movieTitle.
   */
  com.google.protobuf.ByteString
      getMovieTitleBytes();
}
