// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movies.proto

package org.example.client.structs;

/**
 * Protobuf type {@code Movie}
 */
public final class Movie extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Movie)
    MovieOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Movie.newBuilder() to construct.
  private Movie(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Movie() {
    id_ = "";
    plot_ = "";
    genre_ = "";
    cast_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    title_ = "";
    fullplot_ = "";
    countries_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    released_ = "";
    directors_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    rated_ = "";
    lastupdated_ = "";
    type_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Movie();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.client.structs.Movies.internal_static_Movie_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.client.structs.Movies.internal_static_Movie_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.client.structs.Movie.class, org.example.client.structs.Movie.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLOT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object plot_ = "";
  /**
   * <code>string plot = 2;</code>
   * @return The plot.
   */
  @java.lang.Override
  public java.lang.String getPlot() {
    java.lang.Object ref = plot_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      plot_ = s;
      return s;
    }
  }
  /**
   * <code>string plot = 2;</code>
   * @return The bytes for plot.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlotBytes() {
    java.lang.Object ref = plot_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      plot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENRE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object genre_ = "";
  /**
   * <code>string genre = 3;</code>
   * @return The genre.
   */
  @java.lang.Override
  public java.lang.String getGenre() {
    java.lang.Object ref = genre_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      genre_ = s;
      return s;
    }
  }
  /**
   * <code>string genre = 3;</code>
   * @return The bytes for genre.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGenreBytes() {
    java.lang.Object ref = genre_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      genre_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RUNTIME_FIELD_NUMBER = 4;
  private int runtime_ = 0;
  /**
   * <code>int32 runtime = 4;</code>
   * @return The runtime.
   */
  @java.lang.Override
  public int getRuntime() {
    return runtime_;
  }

  public static final int CAST_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList cast_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string cast = 5;</code>
   * @return A list containing the cast.
   */
  public com.google.protobuf.ProtocolStringList
      getCastList() {
    return cast_;
  }
  /**
   * <code>repeated string cast = 5;</code>
   * @return The count of cast.
   */
  public int getCastCount() {
    return cast_.size();
  }
  /**
   * <code>repeated string cast = 5;</code>
   * @param index The index of the element to return.
   * @return The cast at the given index.
   */
  public java.lang.String getCast(int index) {
    return cast_.get(index);
  }
  /**
   * <code>repeated string cast = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the cast at the given index.
   */
  public com.google.protobuf.ByteString
      getCastBytes(int index) {
    return cast_.getByteString(index);
  }

  public static final int NUM_MFLIX_COMMENTS_FIELD_NUMBER = 6;
  private int numMflixComments_ = 0;
  /**
   * <code>int32 num_mflix_comments = 6;</code>
   * @return The numMflixComments.
   */
  @java.lang.Override
  public int getNumMflixComments() {
    return numMflixComments_;
  }

  public static final int TITLE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 7;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 7;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FULLPLOT_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fullplot_ = "";
  /**
   * <code>string fullplot = 8;</code>
   * @return The fullplot.
   */
  @java.lang.Override
  public java.lang.String getFullplot() {
    java.lang.Object ref = fullplot_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fullplot_ = s;
      return s;
    }
  }
  /**
   * <code>string fullplot = 8;</code>
   * @return The bytes for fullplot.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFullplotBytes() {
    java.lang.Object ref = fullplot_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fullplot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUNTRIES_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList countries_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string countries = 9;</code>
   * @return A list containing the countries.
   */
  public com.google.protobuf.ProtocolStringList
      getCountriesList() {
    return countries_;
  }
  /**
   * <code>repeated string countries = 9;</code>
   * @return The count of countries.
   */
  public int getCountriesCount() {
    return countries_.size();
  }
  /**
   * <code>repeated string countries = 9;</code>
   * @param index The index of the element to return.
   * @return The countries at the given index.
   */
  public java.lang.String getCountries(int index) {
    return countries_.get(index);
  }
  /**
   * <code>repeated string countries = 9;</code>
   * @param index The index of the value to return.
   * @return The bytes of the countries at the given index.
   */
  public com.google.protobuf.ByteString
      getCountriesBytes(int index) {
    return countries_.getByteString(index);
  }

  public static final int RELEASED_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object released_ = "";
  /**
   * <code>string released = 10;</code>
   * @return The released.
   */
  @java.lang.Override
  public java.lang.String getReleased() {
    java.lang.Object ref = released_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      released_ = s;
      return s;
    }
  }
  /**
   * <code>string released = 10;</code>
   * @return The bytes for released.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReleasedBytes() {
    java.lang.Object ref = released_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      released_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIRECTORS_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList directors_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string directors = 11;</code>
   * @return A list containing the directors.
   */
  public com.google.protobuf.ProtocolStringList
      getDirectorsList() {
    return directors_;
  }
  /**
   * <code>repeated string directors = 11;</code>
   * @return The count of directors.
   */
  public int getDirectorsCount() {
    return directors_.size();
  }
  /**
   * <code>repeated string directors = 11;</code>
   * @param index The index of the element to return.
   * @return The directors at the given index.
   */
  public java.lang.String getDirectors(int index) {
    return directors_.get(index);
  }
  /**
   * <code>repeated string directors = 11;</code>
   * @param index The index of the value to return.
   * @return The bytes of the directors at the given index.
   */
  public com.google.protobuf.ByteString
      getDirectorsBytes(int index) {
    return directors_.getByteString(index);
  }

  public static final int RATED_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object rated_ = "";
  /**
   * <code>string rated = 12;</code>
   * @return The rated.
   */
  @java.lang.Override
  public java.lang.String getRated() {
    java.lang.Object ref = rated_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rated_ = s;
      return s;
    }
  }
  /**
   * <code>string rated = 12;</code>
   * @return The bytes for rated.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRatedBytes() {
    java.lang.Object ref = rated_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rated_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTUPDATED_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lastupdated_ = "";
  /**
   * <code>string lastupdated = 13;</code>
   * @return The lastupdated.
   */
  @java.lang.Override
  public java.lang.String getLastupdated() {
    java.lang.Object ref = lastupdated_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastupdated_ = s;
      return s;
    }
  }
  /**
   * <code>string lastupdated = 13;</code>
   * @return The bytes for lastupdated.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastupdatedBytes() {
    java.lang.Object ref = lastupdated_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastupdated_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int YEAR_FIELD_NUMBER = 14;
  private int year_ = 0;
  /**
   * <code>int32 year = 14;</code>
   * @return The year.
   */
  @java.lang.Override
  public int getYear() {
    return year_;
  }

  public static final int TYPE_FIELD_NUMBER = 15;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "";
  /**
   * <code>string type = 15;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 15;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(plot_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, plot_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(genre_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, genre_);
    }
    if (runtime_ != 0) {
      output.writeInt32(4, runtime_);
    }
    for (int i = 0; i < cast_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cast_.getRaw(i));
    }
    if (numMflixComments_ != 0) {
      output.writeInt32(6, numMflixComments_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fullplot_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, fullplot_);
    }
    for (int i = 0; i < countries_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, countries_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(released_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, released_);
    }
    for (int i = 0; i < directors_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, directors_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rated_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, rated_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastupdated_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, lastupdated_);
    }
    if (year_ != 0) {
      output.writeInt32(14, year_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, type_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(plot_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, plot_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(genre_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, genre_);
    }
    if (runtime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, runtime_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < cast_.size(); i++) {
        dataSize += computeStringSizeNoTag(cast_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCastList().size();
    }
    if (numMflixComments_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, numMflixComments_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fullplot_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, fullplot_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < countries_.size(); i++) {
        dataSize += computeStringSizeNoTag(countries_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCountriesList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(released_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, released_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < directors_.size(); i++) {
        dataSize += computeStringSizeNoTag(directors_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDirectorsList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rated_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, rated_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastupdated_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, lastupdated_);
    }
    if (year_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, year_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, type_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.client.structs.Movie)) {
      return super.equals(obj);
    }
    org.example.client.structs.Movie other = (org.example.client.structs.Movie) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getPlot()
        .equals(other.getPlot())) return false;
    if (!getGenre()
        .equals(other.getGenre())) return false;
    if (getRuntime()
        != other.getRuntime()) return false;
    if (!getCastList()
        .equals(other.getCastList())) return false;
    if (getNumMflixComments()
        != other.getNumMflixComments()) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getFullplot()
        .equals(other.getFullplot())) return false;
    if (!getCountriesList()
        .equals(other.getCountriesList())) return false;
    if (!getReleased()
        .equals(other.getReleased())) return false;
    if (!getDirectorsList()
        .equals(other.getDirectorsList())) return false;
    if (!getRated()
        .equals(other.getRated())) return false;
    if (!getLastupdated()
        .equals(other.getLastupdated())) return false;
    if (getYear()
        != other.getYear()) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + PLOT_FIELD_NUMBER;
    hash = (53 * hash) + getPlot().hashCode();
    hash = (37 * hash) + GENRE_FIELD_NUMBER;
    hash = (53 * hash) + getGenre().hashCode();
    hash = (37 * hash) + RUNTIME_FIELD_NUMBER;
    hash = (53 * hash) + getRuntime();
    if (getCastCount() > 0) {
      hash = (37 * hash) + CAST_FIELD_NUMBER;
      hash = (53 * hash) + getCastList().hashCode();
    }
    hash = (37 * hash) + NUM_MFLIX_COMMENTS_FIELD_NUMBER;
    hash = (53 * hash) + getNumMflixComments();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + FULLPLOT_FIELD_NUMBER;
    hash = (53 * hash) + getFullplot().hashCode();
    if (getCountriesCount() > 0) {
      hash = (37 * hash) + COUNTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getCountriesList().hashCode();
    }
    hash = (37 * hash) + RELEASED_FIELD_NUMBER;
    hash = (53 * hash) + getReleased().hashCode();
    if (getDirectorsCount() > 0) {
      hash = (37 * hash) + DIRECTORS_FIELD_NUMBER;
      hash = (53 * hash) + getDirectorsList().hashCode();
    }
    hash = (37 * hash) + RATED_FIELD_NUMBER;
    hash = (53 * hash) + getRated().hashCode();
    hash = (37 * hash) + LASTUPDATED_FIELD_NUMBER;
    hash = (53 * hash) + getLastupdated().hashCode();
    hash = (37 * hash) + YEAR_FIELD_NUMBER;
    hash = (53 * hash) + getYear();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.client.structs.Movie parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.client.structs.Movie parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.client.structs.Movie parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.client.structs.Movie parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.client.structs.Movie parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.client.structs.Movie parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.client.structs.Movie parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.client.structs.Movie parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.client.structs.Movie parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.client.structs.Movie parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.client.structs.Movie parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.client.structs.Movie parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.client.structs.Movie prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Movie}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Movie)
      org.example.client.structs.MovieOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.client.structs.Movies.internal_static_Movie_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.client.structs.Movies.internal_static_Movie_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.client.structs.Movie.class, org.example.client.structs.Movie.Builder.class);
    }

    // Construct using org.example.client.structs.Movie.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      plot_ = "";
      genre_ = "";
      runtime_ = 0;
      cast_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      numMflixComments_ = 0;
      title_ = "";
      fullplot_ = "";
      countries_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      released_ = "";
      directors_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      rated_ = "";
      lastupdated_ = "";
      year_ = 0;
      type_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.client.structs.Movies.internal_static_Movie_descriptor;
    }

    @java.lang.Override
    public org.example.client.structs.Movie getDefaultInstanceForType() {
      return org.example.client.structs.Movie.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.client.structs.Movie build() {
      org.example.client.structs.Movie result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.client.structs.Movie buildPartial() {
      org.example.client.structs.Movie result = new org.example.client.structs.Movie(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.client.structs.Movie result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.plot_ = plot_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.genre_ = genre_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.runtime_ = runtime_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        cast_.makeImmutable();
        result.cast_ = cast_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.numMflixComments_ = numMflixComments_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.fullplot_ = fullplot_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        countries_.makeImmutable();
        result.countries_ = countries_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.released_ = released_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        directors_.makeImmutable();
        result.directors_ = directors_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.rated_ = rated_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.lastupdated_ = lastupdated_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.year_ = year_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.type_ = type_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.client.structs.Movie) {
        return mergeFrom((org.example.client.structs.Movie)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.client.structs.Movie other) {
      if (other == org.example.client.structs.Movie.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getPlot().isEmpty()) {
        plot_ = other.plot_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getGenre().isEmpty()) {
        genre_ = other.genre_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getRuntime() != 0) {
        setRuntime(other.getRuntime());
      }
      if (!other.cast_.isEmpty()) {
        if (cast_.isEmpty()) {
          cast_ = other.cast_;
          bitField0_ |= 0x00000010;
        } else {
          ensureCastIsMutable();
          cast_.addAll(other.cast_);
        }
        onChanged();
      }
      if (other.getNumMflixComments() != 0) {
        setNumMflixComments(other.getNumMflixComments());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getFullplot().isEmpty()) {
        fullplot_ = other.fullplot_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.countries_.isEmpty()) {
        if (countries_.isEmpty()) {
          countries_ = other.countries_;
          bitField0_ |= 0x00000100;
        } else {
          ensureCountriesIsMutable();
          countries_.addAll(other.countries_);
        }
        onChanged();
      }
      if (!other.getReleased().isEmpty()) {
        released_ = other.released_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.directors_.isEmpty()) {
        if (directors_.isEmpty()) {
          directors_ = other.directors_;
          bitField0_ |= 0x00000400;
        } else {
          ensureDirectorsIsMutable();
          directors_.addAll(other.directors_);
        }
        onChanged();
      }
      if (!other.getRated().isEmpty()) {
        rated_ = other.rated_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (!other.getLastupdated().isEmpty()) {
        lastupdated_ = other.lastupdated_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (other.getYear() != 0) {
        setYear(other.getYear());
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        bitField0_ |= 0x00004000;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              plot_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              genre_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              runtime_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureCastIsMutable();
              cast_.add(s);
              break;
            } // case 42
            case 48: {
              numMflixComments_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              fullplot_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureCountriesIsMutable();
              countries_.add(s);
              break;
            } // case 74
            case 82: {
              released_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureDirectorsIsMutable();
              directors_.add(s);
              break;
            } // case 90
            case 98: {
              rated_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              lastupdated_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 112: {
              year_ = input.readInt32();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            case 122: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00004000;
              break;
            } // case 122
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object plot_ = "";
    /**
     * <code>string plot = 2;</code>
     * @return The plot.
     */
    public java.lang.String getPlot() {
      java.lang.Object ref = plot_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        plot_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string plot = 2;</code>
     * @return The bytes for plot.
     */
    public com.google.protobuf.ByteString
        getPlotBytes() {
      java.lang.Object ref = plot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        plot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string plot = 2;</code>
     * @param value The plot to set.
     * @return This builder for chaining.
     */
    public Builder setPlot(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      plot_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string plot = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlot() {
      plot_ = getDefaultInstance().getPlot();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string plot = 2;</code>
     * @param value The bytes for plot to set.
     * @return This builder for chaining.
     */
    public Builder setPlotBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      plot_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object genre_ = "";
    /**
     * <code>string genre = 3;</code>
     * @return The genre.
     */
    public java.lang.String getGenre() {
      java.lang.Object ref = genre_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        genre_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string genre = 3;</code>
     * @return The bytes for genre.
     */
    public com.google.protobuf.ByteString
        getGenreBytes() {
      java.lang.Object ref = genre_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genre_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string genre = 3;</code>
     * @param value The genre to set.
     * @return This builder for chaining.
     */
    public Builder setGenre(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      genre_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string genre = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGenre() {
      genre_ = getDefaultInstance().getGenre();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string genre = 3;</code>
     * @param value The bytes for genre to set.
     * @return This builder for chaining.
     */
    public Builder setGenreBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      genre_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int runtime_ ;
    /**
     * <code>int32 runtime = 4;</code>
     * @return The runtime.
     */
    @java.lang.Override
    public int getRuntime() {
      return runtime_;
    }
    /**
     * <code>int32 runtime = 4;</code>
     * @param value The runtime to set.
     * @return This builder for chaining.
     */
    public Builder setRuntime(int value) {

      runtime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 runtime = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRuntime() {
      bitField0_ = (bitField0_ & ~0x00000008);
      runtime_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList cast_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureCastIsMutable() {
      if (!cast_.isModifiable()) {
        cast_ = new com.google.protobuf.LazyStringArrayList(cast_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <code>repeated string cast = 5;</code>
     * @return A list containing the cast.
     */
    public com.google.protobuf.ProtocolStringList
        getCastList() {
      cast_.makeImmutable();
      return cast_;
    }
    /**
     * <code>repeated string cast = 5;</code>
     * @return The count of cast.
     */
    public int getCastCount() {
      return cast_.size();
    }
    /**
     * <code>repeated string cast = 5;</code>
     * @param index The index of the element to return.
     * @return The cast at the given index.
     */
    public java.lang.String getCast(int index) {
      return cast_.get(index);
    }
    /**
     * <code>repeated string cast = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the cast at the given index.
     */
    public com.google.protobuf.ByteString
        getCastBytes(int index) {
      return cast_.getByteString(index);
    }
    /**
     * <code>repeated string cast = 5;</code>
     * @param index The index to set the value at.
     * @param value The cast to set.
     * @return This builder for chaining.
     */
    public Builder setCast(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCastIsMutable();
      cast_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cast = 5;</code>
     * @param value The cast to add.
     * @return This builder for chaining.
     */
    public Builder addCast(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCastIsMutable();
      cast_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cast = 5;</code>
     * @param values The cast to add.
     * @return This builder for chaining.
     */
    public Builder addAllCast(
        java.lang.Iterable<java.lang.String> values) {
      ensureCastIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, cast_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cast = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCast() {
      cast_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cast = 5;</code>
     * @param value The bytes of the cast to add.
     * @return This builder for chaining.
     */
    public Builder addCastBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureCastIsMutable();
      cast_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int numMflixComments_ ;
    /**
     * <code>int32 num_mflix_comments = 6;</code>
     * @return The numMflixComments.
     */
    @java.lang.Override
    public int getNumMflixComments() {
      return numMflixComments_;
    }
    /**
     * <code>int32 num_mflix_comments = 6;</code>
     * @param value The numMflixComments to set.
     * @return This builder for chaining.
     */
    public Builder setNumMflixComments(int value) {

      numMflixComments_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 num_mflix_comments = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumMflixComments() {
      bitField0_ = (bitField0_ & ~0x00000020);
      numMflixComments_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 7;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 7;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 7;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 7;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object fullplot_ = "";
    /**
     * <code>string fullplot = 8;</code>
     * @return The fullplot.
     */
    public java.lang.String getFullplot() {
      java.lang.Object ref = fullplot_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fullplot_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fullplot = 8;</code>
     * @return The bytes for fullplot.
     */
    public com.google.protobuf.ByteString
        getFullplotBytes() {
      java.lang.Object ref = fullplot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullplot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fullplot = 8;</code>
     * @param value The fullplot to set.
     * @return This builder for chaining.
     */
    public Builder setFullplot(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fullplot_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string fullplot = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearFullplot() {
      fullplot_ = getDefaultInstance().getFullplot();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string fullplot = 8;</code>
     * @param value The bytes for fullplot to set.
     * @return This builder for chaining.
     */
    public Builder setFullplotBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fullplot_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList countries_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureCountriesIsMutable() {
      if (!countries_.isModifiable()) {
        countries_ = new com.google.protobuf.LazyStringArrayList(countries_);
      }
      bitField0_ |= 0x00000100;
    }
    /**
     * <code>repeated string countries = 9;</code>
     * @return A list containing the countries.
     */
    public com.google.protobuf.ProtocolStringList
        getCountriesList() {
      countries_.makeImmutable();
      return countries_;
    }
    /**
     * <code>repeated string countries = 9;</code>
     * @return The count of countries.
     */
    public int getCountriesCount() {
      return countries_.size();
    }
    /**
     * <code>repeated string countries = 9;</code>
     * @param index The index of the element to return.
     * @return The countries at the given index.
     */
    public java.lang.String getCountries(int index) {
      return countries_.get(index);
    }
    /**
     * <code>repeated string countries = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the countries at the given index.
     */
    public com.google.protobuf.ByteString
        getCountriesBytes(int index) {
      return countries_.getByteString(index);
    }
    /**
     * <code>repeated string countries = 9;</code>
     * @param index The index to set the value at.
     * @param value The countries to set.
     * @return This builder for chaining.
     */
    public Builder setCountries(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCountriesIsMutable();
      countries_.set(index, value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string countries = 9;</code>
     * @param value The countries to add.
     * @return This builder for chaining.
     */
    public Builder addCountries(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCountriesIsMutable();
      countries_.add(value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string countries = 9;</code>
     * @param values The countries to add.
     * @return This builder for chaining.
     */
    public Builder addAllCountries(
        java.lang.Iterable<java.lang.String> values) {
      ensureCountriesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, countries_);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string countries = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearCountries() {
      countries_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000100);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string countries = 9;</code>
     * @param value The bytes of the countries to add.
     * @return This builder for chaining.
     */
    public Builder addCountriesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureCountriesIsMutable();
      countries_.add(value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object released_ = "";
    /**
     * <code>string released = 10;</code>
     * @return The released.
     */
    public java.lang.String getReleased() {
      java.lang.Object ref = released_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        released_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string released = 10;</code>
     * @return The bytes for released.
     */
    public com.google.protobuf.ByteString
        getReleasedBytes() {
      java.lang.Object ref = released_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        released_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string released = 10;</code>
     * @param value The released to set.
     * @return This builder for chaining.
     */
    public Builder setReleased(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      released_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string released = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearReleased() {
      released_ = getDefaultInstance().getReleased();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string released = 10;</code>
     * @param value The bytes for released to set.
     * @return This builder for chaining.
     */
    public Builder setReleasedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      released_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList directors_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureDirectorsIsMutable() {
      if (!directors_.isModifiable()) {
        directors_ = new com.google.protobuf.LazyStringArrayList(directors_);
      }
      bitField0_ |= 0x00000400;
    }
    /**
     * <code>repeated string directors = 11;</code>
     * @return A list containing the directors.
     */
    public com.google.protobuf.ProtocolStringList
        getDirectorsList() {
      directors_.makeImmutable();
      return directors_;
    }
    /**
     * <code>repeated string directors = 11;</code>
     * @return The count of directors.
     */
    public int getDirectorsCount() {
      return directors_.size();
    }
    /**
     * <code>repeated string directors = 11;</code>
     * @param index The index of the element to return.
     * @return The directors at the given index.
     */
    public java.lang.String getDirectors(int index) {
      return directors_.get(index);
    }
    /**
     * <code>repeated string directors = 11;</code>
     * @param index The index of the value to return.
     * @return The bytes of the directors at the given index.
     */
    public com.google.protobuf.ByteString
        getDirectorsBytes(int index) {
      return directors_.getByteString(index);
    }
    /**
     * <code>repeated string directors = 11;</code>
     * @param index The index to set the value at.
     * @param value The directors to set.
     * @return This builder for chaining.
     */
    public Builder setDirectors(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDirectorsIsMutable();
      directors_.set(index, value);
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string directors = 11;</code>
     * @param value The directors to add.
     * @return This builder for chaining.
     */
    public Builder addDirectors(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDirectorsIsMutable();
      directors_.add(value);
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string directors = 11;</code>
     * @param values The directors to add.
     * @return This builder for chaining.
     */
    public Builder addAllDirectors(
        java.lang.Iterable<java.lang.String> values) {
      ensureDirectorsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, directors_);
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string directors = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirectors() {
      directors_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000400);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string directors = 11;</code>
     * @param value The bytes of the directors to add.
     * @return This builder for chaining.
     */
    public Builder addDirectorsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureDirectorsIsMutable();
      directors_.add(value);
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private java.lang.Object rated_ = "";
    /**
     * <code>string rated = 12;</code>
     * @return The rated.
     */
    public java.lang.String getRated() {
      java.lang.Object ref = rated_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rated_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string rated = 12;</code>
     * @return The bytes for rated.
     */
    public com.google.protobuf.ByteString
        getRatedBytes() {
      java.lang.Object ref = rated_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rated_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string rated = 12;</code>
     * @param value The rated to set.
     * @return This builder for chaining.
     */
    public Builder setRated(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      rated_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>string rated = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearRated() {
      rated_ = getDefaultInstance().getRated();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <code>string rated = 12;</code>
     * @param value The bytes for rated to set.
     * @return This builder for chaining.
     */
    public Builder setRatedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      rated_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private java.lang.Object lastupdated_ = "";
    /**
     * <code>string lastupdated = 13;</code>
     * @return The lastupdated.
     */
    public java.lang.String getLastupdated() {
      java.lang.Object ref = lastupdated_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastupdated_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lastupdated = 13;</code>
     * @return The bytes for lastupdated.
     */
    public com.google.protobuf.ByteString
        getLastupdatedBytes() {
      java.lang.Object ref = lastupdated_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastupdated_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lastupdated = 13;</code>
     * @param value The lastupdated to set.
     * @return This builder for chaining.
     */
    public Builder setLastupdated(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lastupdated_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>string lastupdated = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastupdated() {
      lastupdated_ = getDefaultInstance().getLastupdated();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <code>string lastupdated = 13;</code>
     * @param value The bytes for lastupdated to set.
     * @return This builder for chaining.
     */
    public Builder setLastupdatedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lastupdated_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private int year_ ;
    /**
     * <code>int32 year = 14;</code>
     * @return The year.
     */
    @java.lang.Override
    public int getYear() {
      return year_;
    }
    /**
     * <code>int32 year = 14;</code>
     * @param value The year to set.
     * @return This builder for chaining.
     */
    public Builder setYear(int value) {

      year_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 year = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearYear() {
      bitField0_ = (bitField0_ & ~0x00002000);
      year_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 15;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 15;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 15;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00004000);
      onChanged();
      return this;
    }
    /**
     * <code>string type = 15;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Movie)
  }

  // @@protoc_insertion_point(class_scope:Movie)
  private static final org.example.client.structs.Movie DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.client.structs.Movie();
  }

  public static org.example.client.structs.Movie getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Movie>
      PARSER = new com.google.protobuf.AbstractParser<Movie>() {
    @java.lang.Override
    public Movie parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Movie> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Movie> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.client.structs.Movie getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

