// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movies.proto

package org.example.client.structs;

/**
 * Protobuf enum {@code Operations}
 */
public enum Operations
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Zero = 0;</code>
   */
  Zero(0),
  /**
   * <code>Create = 1;</code>
   */
  Create(1),
  /**
   * <code>Read = 2;</code>
   */
  Read(2),
  /**
   * <code>Update = 3;</code>
   */
  Update(3),
  /**
   * <code>Delete = 4;</code>
   */
  Delete(4),
  /**
   * <code>ListByActor = 5;</code>
   */
  ListByActor(5),
  /**
   * <code>ListByGenre = 6;</code>
   */
  ListByGenre(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Zero = 0;</code>
   */
  public static final int Zero_VALUE = 0;
  /**
   * <code>Create = 1;</code>
   */
  public static final int Create_VALUE = 1;
  /**
   * <code>Read = 2;</code>
   */
  public static final int Read_VALUE = 2;
  /**
   * <code>Update = 3;</code>
   */
  public static final int Update_VALUE = 3;
  /**
   * <code>Delete = 4;</code>
   */
  public static final int Delete_VALUE = 4;
  /**
   * <code>ListByActor = 5;</code>
   */
  public static final int ListByActor_VALUE = 5;
  /**
   * <code>ListByGenre = 6;</code>
   */
  public static final int ListByGenre_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Operations valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Operations forNumber(int value) {
    switch (value) {
      case 0: return Zero;
      case 1: return Create;
      case 2: return Read;
      case 3: return Update;
      case 4: return Delete;
      case 5: return ListByActor;
      case 6: return ListByGenre;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Operations>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Operations> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Operations>() {
          public Operations findValueByNumber(int number) {
            return Operations.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.example.client.structs.Movies.getDescriptor().getEnumTypes().get(0);
  }

  private static final Operations[] VALUES = values();

  public static Operations valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Operations(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Operations)
}

