// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movies.proto

package org.example.client.structs;

public interface ServerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   * @return The response.
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   * @return The bytes for response.
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
