// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movies.proto

package org.example.client.structs;

/**
 * Protobuf type {@code ServerListBy}
 */
public final class ServerListBy extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ServerListBy)
    ServerListByOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServerListBy.newBuilder() to construct.
  private ServerListBy(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerListBy() {
    movies_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServerListBy();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.client.structs.Movies.internal_static_ServerListBy_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.client.structs.Movies.internal_static_ServerListBy_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.client.structs.ServerListBy.class, org.example.client.structs.ServerListBy.Builder.class);
  }

  public static final int MOVIES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.example.client.structs.Movie> movies_;
  /**
   * <code>repeated .Movie movies = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.example.client.structs.Movie> getMoviesList() {
    return movies_;
  }
  /**
   * <code>repeated .Movie movies = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.example.client.structs.MovieOrBuilder> 
      getMoviesOrBuilderList() {
    return movies_;
  }
  /**
   * <code>repeated .Movie movies = 1;</code>
   */
  @java.lang.Override
  public int getMoviesCount() {
    return movies_.size();
  }
  /**
   * <code>repeated .Movie movies = 1;</code>
   */
  @java.lang.Override
  public org.example.client.structs.Movie getMovies(int index) {
    return movies_.get(index);
  }
  /**
   * <code>repeated .Movie movies = 1;</code>
   */
  @java.lang.Override
  public org.example.client.structs.MovieOrBuilder getMoviesOrBuilder(
      int index) {
    return movies_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < movies_.size(); i++) {
      output.writeMessage(1, movies_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < movies_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, movies_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.client.structs.ServerListBy)) {
      return super.equals(obj);
    }
    org.example.client.structs.ServerListBy other = (org.example.client.structs.ServerListBy) obj;

    if (!getMoviesList()
        .equals(other.getMoviesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMoviesCount() > 0) {
      hash = (37 * hash) + MOVIES_FIELD_NUMBER;
      hash = (53 * hash) + getMoviesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.client.structs.ServerListBy parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.client.structs.ServerListBy parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.client.structs.ServerListBy parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.client.structs.ServerListBy parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.client.structs.ServerListBy parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.client.structs.ServerListBy parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.client.structs.ServerListBy parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.client.structs.ServerListBy parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.client.structs.ServerListBy parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.client.structs.ServerListBy parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.client.structs.ServerListBy parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.client.structs.ServerListBy parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.client.structs.ServerListBy prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ServerListBy}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ServerListBy)
      org.example.client.structs.ServerListByOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.client.structs.Movies.internal_static_ServerListBy_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.client.structs.Movies.internal_static_ServerListBy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.client.structs.ServerListBy.class, org.example.client.structs.ServerListBy.Builder.class);
    }

    // Construct using org.example.client.structs.ServerListBy.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (moviesBuilder_ == null) {
        movies_ = java.util.Collections.emptyList();
      } else {
        movies_ = null;
        moviesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.client.structs.Movies.internal_static_ServerListBy_descriptor;
    }

    @java.lang.Override
    public org.example.client.structs.ServerListBy getDefaultInstanceForType() {
      return org.example.client.structs.ServerListBy.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.client.structs.ServerListBy build() {
      org.example.client.structs.ServerListBy result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.client.structs.ServerListBy buildPartial() {
      org.example.client.structs.ServerListBy result = new org.example.client.structs.ServerListBy(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.example.client.structs.ServerListBy result) {
      if (moviesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          movies_ = java.util.Collections.unmodifiableList(movies_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.movies_ = movies_;
      } else {
        result.movies_ = moviesBuilder_.build();
      }
    }

    private void buildPartial0(org.example.client.structs.ServerListBy result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.client.structs.ServerListBy) {
        return mergeFrom((org.example.client.structs.ServerListBy)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.client.structs.ServerListBy other) {
      if (other == org.example.client.structs.ServerListBy.getDefaultInstance()) return this;
      if (moviesBuilder_ == null) {
        if (!other.movies_.isEmpty()) {
          if (movies_.isEmpty()) {
            movies_ = other.movies_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMoviesIsMutable();
            movies_.addAll(other.movies_);
          }
          onChanged();
        }
      } else {
        if (!other.movies_.isEmpty()) {
          if (moviesBuilder_.isEmpty()) {
            moviesBuilder_.dispose();
            moviesBuilder_ = null;
            movies_ = other.movies_;
            bitField0_ = (bitField0_ & ~0x00000001);
            moviesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMoviesFieldBuilder() : null;
          } else {
            moviesBuilder_.addAllMessages(other.movies_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.example.client.structs.Movie m =
                  input.readMessage(
                      org.example.client.structs.Movie.parser(),
                      extensionRegistry);
              if (moviesBuilder_ == null) {
                ensureMoviesIsMutable();
                movies_.add(m);
              } else {
                moviesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.example.client.structs.Movie> movies_ =
      java.util.Collections.emptyList();
    private void ensureMoviesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        movies_ = new java.util.ArrayList<org.example.client.structs.Movie>(movies_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.client.structs.Movie, org.example.client.structs.Movie.Builder, org.example.client.structs.MovieOrBuilder> moviesBuilder_;

    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public java.util.List<org.example.client.structs.Movie> getMoviesList() {
      if (moviesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(movies_);
      } else {
        return moviesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public int getMoviesCount() {
      if (moviesBuilder_ == null) {
        return movies_.size();
      } else {
        return moviesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public org.example.client.structs.Movie getMovies(int index) {
      if (moviesBuilder_ == null) {
        return movies_.get(index);
      } else {
        return moviesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder setMovies(
        int index, org.example.client.structs.Movie value) {
      if (moviesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMoviesIsMutable();
        movies_.set(index, value);
        onChanged();
      } else {
        moviesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder setMovies(
        int index, org.example.client.structs.Movie.Builder builderForValue) {
      if (moviesBuilder_ == null) {
        ensureMoviesIsMutable();
        movies_.set(index, builderForValue.build());
        onChanged();
      } else {
        moviesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder addMovies(org.example.client.structs.Movie value) {
      if (moviesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMoviesIsMutable();
        movies_.add(value);
        onChanged();
      } else {
        moviesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder addMovies(
        int index, org.example.client.structs.Movie value) {
      if (moviesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMoviesIsMutable();
        movies_.add(index, value);
        onChanged();
      } else {
        moviesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder addMovies(
        org.example.client.structs.Movie.Builder builderForValue) {
      if (moviesBuilder_ == null) {
        ensureMoviesIsMutable();
        movies_.add(builderForValue.build());
        onChanged();
      } else {
        moviesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder addMovies(
        int index, org.example.client.structs.Movie.Builder builderForValue) {
      if (moviesBuilder_ == null) {
        ensureMoviesIsMutable();
        movies_.add(index, builderForValue.build());
        onChanged();
      } else {
        moviesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder addAllMovies(
        java.lang.Iterable<? extends org.example.client.structs.Movie> values) {
      if (moviesBuilder_ == null) {
        ensureMoviesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, movies_);
        onChanged();
      } else {
        moviesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder clearMovies() {
      if (moviesBuilder_ == null) {
        movies_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        moviesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public Builder removeMovies(int index) {
      if (moviesBuilder_ == null) {
        ensureMoviesIsMutable();
        movies_.remove(index);
        onChanged();
      } else {
        moviesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public org.example.client.structs.Movie.Builder getMoviesBuilder(
        int index) {
      return getMoviesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public org.example.client.structs.MovieOrBuilder getMoviesOrBuilder(
        int index) {
      if (moviesBuilder_ == null) {
        return movies_.get(index);  } else {
        return moviesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public java.util.List<? extends org.example.client.structs.MovieOrBuilder> 
         getMoviesOrBuilderList() {
      if (moviesBuilder_ != null) {
        return moviesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(movies_);
      }
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public org.example.client.structs.Movie.Builder addMoviesBuilder() {
      return getMoviesFieldBuilder().addBuilder(
          org.example.client.structs.Movie.getDefaultInstance());
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public org.example.client.structs.Movie.Builder addMoviesBuilder(
        int index) {
      return getMoviesFieldBuilder().addBuilder(
          index, org.example.client.structs.Movie.getDefaultInstance());
    }
    /**
     * <code>repeated .Movie movies = 1;</code>
     */
    public java.util.List<org.example.client.structs.Movie.Builder> 
         getMoviesBuilderList() {
      return getMoviesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.client.structs.Movie, org.example.client.structs.Movie.Builder, org.example.client.structs.MovieOrBuilder> 
        getMoviesFieldBuilder() {
      if (moviesBuilder_ == null) {
        moviesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.example.client.structs.Movie, org.example.client.structs.Movie.Builder, org.example.client.structs.MovieOrBuilder>(
                movies_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        movies_ = null;
      }
      return moviesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ServerListBy)
  }

  // @@protoc_insertion_point(class_scope:ServerListBy)
  private static final org.example.client.structs.ServerListBy DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.client.structs.ServerListBy();
  }

  public static org.example.client.structs.ServerListBy getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerListBy>
      PARSER = new com.google.protobuf.AbstractParser<ServerListBy>() {
    @java.lang.Override
    public ServerListBy parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ServerListBy> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerListBy> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.client.structs.ServerListBy getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

