// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movies.proto

package org.example.client.structs;

public interface ServerListByOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServerListBy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Movie movies = 1;</code>
   */
  java.util.List<org.example.client.structs.Movie> 
      getMoviesList();
  /**
   * <code>repeated .Movie movies = 1;</code>
   */
  org.example.client.structs.Movie getMovies(int index);
  /**
   * <code>repeated .Movie movies = 1;</code>
   */
  int getMoviesCount();
  /**
   * <code>repeated .Movie movies = 1;</code>
   */
  java.util.List<? extends org.example.client.structs.MovieOrBuilder> 
      getMoviesOrBuilderList();
  /**
   * <code>repeated .Movie movies = 1;</code>
   */
  org.example.client.structs.MovieOrBuilder getMoviesOrBuilder(
      int index);
}
